-- Enable necessary extensions
create extension if not exists "uuid-ossp";

-- Enums
create type app_role as enum ('student', 'staff_member', 'technician', 'admin');
create type facility_type as enum ('Hostel', 'Lecture Hall', 'Laboratory', 'Office', 'Sports Complex', 'Chapel', 'Other');
create type ticket_status as enum ('Pending', 'Assigned', 'In Progress', 'Resolved');
create type ticket_priority as enum ('Low', 'Medium', 'High');

-- Profiles Table (Extends Supabase Auth)
create table profiles (
  id uuid references auth.users on delete cascade primary key,
  full_name text,
  email text,
  role app_role default 'student',
  identification_number text, -- Matric No or Staff ID
  department text, -- For staff
  skills text[], -- For technicians
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Tickets Table
create table tickets (
  id bigint generated by default as identity primary key,
  title text not null,
  description text not null,
  category text not null, -- Electrical, Plumbing, etc.
  facility_type facility_type not null,
  specific_location text not null,
  status ticket_status default 'Pending',
  priority ticket_priority default 'Medium',
  image_url text,
  user_id uuid references profiles(id) not null,
  assigned_to uuid references profiles(id),
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Notifications Table
create table notifications (
  id bigint generated by default as identity primary key,
  user_id uuid references profiles(id) not null,
  message text not null,
  is_read boolean default false,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- RLS Policies
alter table profiles enable row level security;
alter table tickets enable row level security;
alter table notifications enable row level security;

-- Profiles Policies
create policy "Public profiles are viewable by everyone" on profiles for select using (true);
create policy "Users can insert their own profile" on profiles for insert with check (auth.uid() = id);
create policy "Users can update own profile" on profiles for update using (auth.uid() = id);

-- Tickets Policies
create policy "Users can view their own tickets" on tickets for select using (auth.uid() = user_id);
create policy "Staff/Admins/Technicians can view all tickets" on tickets for select using (
  exists (select 1 from profiles where id = auth.uid() and role in ('staff_member', 'admin', 'technician'))
);
create policy "Users can create tickets" on tickets for insert with check (auth.uid() = user_id);
create policy "Technicians/Admins can update tickets" on tickets for update using (
  exists (select 1 from profiles where id = auth.uid() and role in ('admin', 'technician'))
);

-- Auto-Assignment Trigger Function
create or replace function auto_assign_technician()
returns trigger as $$
declare
  tech_id uuid;
begin
  -- Find technician with matching skill and lowest active ticket count
  select id into tech_id
  from profiles p
  left join tickets t on t.assigned_to = p.id and t.status != 'Resolved'
  where p.role = 'technician'
  and new.category = any(p.skills)
  group by p.id
  order by count(t.id) asc
  limit 1;

  if tech_id is not null then
    new.assigned_to := tech_id;
    new.status := 'Assigned';
  end if;

  return new;
end;
$$ language plpgsql security definer;

-- Trigger
create trigger on_ticket_created
  before insert on tickets
  for each row execute procedure auto_assign_technician();
